academico/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    # urls para la aplicacion home
    url(r'^', include('applications.home.urls', namespace="home_app")),

    #url para administrador
    url(r'^admin/', admin.site.urls),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/home/urls.py
# django
from django.conf.urls import include, url

# local
from . import views


urlpatterns = [
    url(
        r'^$',
        views.IndexView.as_view(),
        name="inicio"
    ),
    url(
        r'^entrada/lista-entradas/$',
        views.EntryListView.as_view(),
        name="entrada-lista"
    ),
    url(
        r'^entrada/buscar/$',
        views.EntryBuscarListView.as_view(),
        name="entrada-buscar"
    ),
    #url para mostrar resultdos de filtro
    url(
        r'^lista-de-entradas-segun-flitro/(?P<filtro>[-\w]+)/$',
        views.EntryFilterView.as_view(),
        name="entrada-filtro"
    ),
    url(
        r'^entrada/(?P<slug>[-\w]+)/$',
        views.EntryDetailView.as_view(),
        name="entrada-detalle"
    ),
    url(
        r'^agregar-sugencia/$',
        views.SugerenciaCreateView.as_view(),
        name="sugerencia-add"
    ),
    url(
        r'^lista-de-sugerencias/$',
        views.ListaSugerenciaView.as_view(),
        name="sugerencia-list"
    ),
    url(
        r'^entradas-con-suscripcion/$',
        views.ListaConFormView.as_view(),
        name="entrada-suscripcion"
    ),

]

applications/home/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.template.defaultfilters import slugify
from django.utils.encoding import python_2_unicode_compatible

#import thryparty
from ckeditor.fields import RichTextField

@python_2_unicode_compatible
class Category(models.Model):
    name = models.CharField('nombre', max_length=50, unique=True)
    slug = models.SlugField(editable=False)

    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)


@python_2_unicode_compatible
class Entry(models.Model):

    title = models.CharField('titulo', max_length=200)
    content = RichTextField('contenido')
    image = models.ImageField(upload_to='blog', verbose_name='imagen')
    created = models.DateField('Fecha de creacion', auto_now_add=True)
    category = models.ManyToManyField(Category, verbose_name='categoria(s)')
    views = models.PositiveIntegerField('visitas', default=0)
    slug = models.SlugField(editable=False)

    class Meta:
        verbose_name = 'Entrada'
        verbose_name_plural = 'Entradas'
        ordering = ["-created"]

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.title)
        super(Entry, self).save(*args, **kwargs)


@python_2_unicode_compatible
class Sugerencia(models.Model):

    title = models.CharField('Titulo', max_length=300)
    contenido = models.TextField(blank=True)
    name = models.CharField('Nombre',max_length=200)
    email = models.EmailField()

    class Meta:
        verbose_name = 'Sugerencia'
        verbose_name_plural = 'Sugerencias'

    def __str__(self):
        return self.title


@python_2_unicode_compatible
class Subscription(models.Model):
    first_name = models.CharField('nombres', max_length=50, null=True)
    last_name = models.CharField('apellidos', max_length=50, null=True)
    email = models.EmailField('E-mail', max_length=50, unique=True)
    class Meta:
        verbose_name = 'Suscripcion'
        verbose_name_plural = 'Suscripciones'

    def __str__(self):
        return self.first_name


# @python_2_unicode_compatible
# class Contacto(models.Model):
#     name = models.CharField('nombre', max_length=50)
#     email = models.EmailField('E-mail')
#     phone = models.CharField('Telefono', max_length=50)
#     business = models.CharField('Asunto', max_length=50)
#     horario = models.CharField('Sugiera una Hora Para Contactarlo', max_length=50)
#     menssage = models.CharField('¿Cual es tu Consulta?', max_length=200)

#     class Meta:
#         verbose_name = 'Contacto'
#         verbose_name_plural = 'Contactenos'

#     def __str__(self):
#         return self.name

applications/home/forms.py
# -*- encoding: utf-8 -*-
from django import forms

from .models import Sugerencia, Subscription

class BuscarForm(forms.Form):
    buscar = forms.CharField(
        label='Search',
        widget=forms.TextInput(
            attrs={
                'placeholder': 'busca una entrada ..',
            }
        )
    )


class SugerenciaForm(forms.ModelForm):

    class Meta:
        model = Sugerencia
        fields = (
            'title',
            'contenido',
            'name',
            'email',
        )


class SuscripcionForm(forms.Form):
    first_name = forms.CharField(
        label='Su Nombre',
        max_length='70',
        required=False,
    )
    last_name = forms.CharField(
        label='Su Apellido',
        max_length='50', required=False)
    email = forms.EmailField(
        label='Su E-mail',
        max_length='70',
        required=False,
    )


class SuscripcionForm2(forms.ModelForm):

    class Meta:
        model = Subscription
        fields = (
            'first_name',
            'last_name',
            'email',
        )


# class ContactoForm(forms.ModelForm):

#     class Meta:
#         model = Zone
#         fields = (
#             'name',
#         )
#         widgets = {
#             'name': forms.TextInput(
#                 attrs={
#                     'placeholder': 'Nombre de ...',
#                 }
#             ),
#         }

#     def clean_name(self):
#         name = self.cleaned_data['name']
#         if Zone.objects.filter(name=name, state=False).count() > 0:
#             msj = 'el nombre de zona ya existe'
#             self.add_error('name', msj)
#         return name

applications/home/views.py
# -*- coding: utf-8 -*-
# django
from django.views.generic import ListView
from django.views.generic import (
    DetailView,
    TemplateView,
    DeleteView,
    UpdateView,
    CreateView,
)
from django.views.generic.edit import FormMixin
from django.core.urlresolvers import reverse_lazy, reverse

#app home
from .models import Category, Entry, Sugerencia, Subscription
from .forms import BuscarForm, SugerenciaForm, SuscripcionForm, SuscripcionForm2


class IndexView(TemplateView):
    """ vista que carga pantalla principal """
    template_name = 'home/index.html'


class EntryListView(ListView):
    """vista que lista entradas"""
    context_object_name = 'entradas'
    paginate_by = 8
    template_name = 'home/list_entrada.html'

    def get_context_data(self, **kwargs):
        context = super(EntryListView, self).get_context_data(**kwargs)
        context['categorys'] = Category.objects.order_by('name')
        return context

    def get_queryset(self):
        return Entry.objects.order_by('-created')


class EntryFilterView(ListView):
    """vista que lista entradas por un filtro"""
    context_object_name = 'entradas'
    paginate_by = 8
    template_name = 'home/filtro.html'

    def get_context_data(self, **kwargs):
        context = super(EntryFilterView, self).get_context_data(**kwargs)
        context['categorys'] = Category.objects.order_by('name')
        context['categoria'] = self.kwargs.get('filtro', 0)
        return context

    def get_queryset(self):
        categoria = self.kwargs.get('filtro', 0)
        return Entry.objects.filter(
            category__name=categoria,
        )


class EntryDetailView(DetailView):
    """vista que muetra el detalle de una entrada"""
    model = Entry
    template_name = 'home/detail_entrada.html'


class EntryBuscarListView(ListView):
    """vista que busca una entrada"""
    context_object_name = 'entradas'
    #paginate_by = 8
    template_name = 'home/lista.html'

    def get_context_data(self, **kwargs):
        context = super(EntryBuscarListView, self).get_context_data(**kwargs)
        context['form'] = BuscarForm
        return context

    def get_queryset(self):
        q = self.request.GET.get("buscar", '')
        return Entry.objects.filter(
            title__icontains=q,
        )


class SugerenciaCreateView(CreateView):
    model = Sugerencia
    form_class = SugerenciaForm
    success_url = reverse_lazy('home_app:sugerencia-list')
    template_name = 'home/add_sugerencia.html'


class ListaSugerenciaView(ListView):
    context_object_name = 'sugerencias'
    template_name = 'home/lista_sugerencia.html'

    def get_queryset(self):
        return Sugerencia.objects.all()


class ListaConFormView(FormMixin, ListView):
    context_object_name = 'lista_entradas'
    template_name = 'home/lista_form.html'
    paginate_by = 4
    form_class = SuscripcionForm2
    success_url = '.'

    def get_queryset(self):
        return Entry.objects.order_by('-created')

    def post(self, request, *args, **kwargs):
        print '************************'
        print request
        form = self.get_form()
        if form.is_valid():
            print 'Formulario valido'
            return self.form_valid(form)
        else:
            print 'Formulario no valido'  
            return self.form_invalid(form)
#
    def form_valid(self, form):
        # ********este procedimiento se usa siempre cuando se trabaja con un form.Form******
        # nombre = form.cleaned_data['first_name']
        # apellido = form.cleaned_data['last_name']
        # correo = form.cleaned_data['email']
        # #validamos si el email existe
        # #if Subscription.objects.filter(email=user).count()==0:
        # subscription = Subscription(
        #     first_name=nombre,
        #     last_name=apellido,
        #     email=correo,
        # )
        # subscription.save()

        #****este procedimiento se utiliza generalmente al tabajar con form.ModelForm*****
        form.save()
        return super(ListaConFormView, self).form_valid(form)


# class ContactoCreateView(CreateView):
#     model = Contacto
#     form_class = ContactoForm
#     success_url = '.'
#     template_name = 'home/contacto.html'

templates/home/add_sugerencia.html
{% extends "home/base_home.html" %}

{% load staticfiles %}

{% block title %} Agregar Sugerencia {% endblock title %}

{% block content %}

  <h1>Nueva Sugerencia</h1>

  <form role="form" method="POST" enctype="multipart/form-data">{% csrf_token %}
  
  {{form}}

  <button type="submit">Guardar</button>
 </form>

{% endblock content %}

templates/home/base_home.html
{% extends "base.html" %}

{% load staticfiles %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/materialize.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
{% endblock css %}

{% block js %}
    <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="{% static 'js/materialize.min.js' %}"></script>
    <script src="{% static 'js/script.js' %}"></script>

{% endblock js %}

templates/home/buscar.html
{% extends "home/base_home.html" %}

{% load staticfiles %}

{% block title %} Lista de entradas {% endblock title %}

{% block content %}
<div class="container">
<h1>Lista de Entradas</h1>

<form method="get" class="form-horizontal">{% csrf_token %}
    <div class="row">
        <div class="medium-4 columns">
                {{form.buscar}}
        </div>
    </div>
</form>

{% for e in entradas  %}
  <div class="row">
    <div class="col s12 m7">
      <div class="card small">
        <div class="card-image">
          <img src="{{ e.image.url }}">
          <span class="card-title">{{e.title}}</span>
        </div>
        <div class="card-content">
          <p>{{e.content|safe|truncatechars_html:300}}</p>
        </div>
        <div class="card-action">
          <a href="{% url 'home_app:entrada-detalle' e.slug %}">Ver Mas</a>
        </div>
      </div>
    </div>
  </div>
{% endfor %}
</div>
{% endblock content %}

templates/home/detail_entrada.html
{% extends "home/base_home.html" %}

{% load staticfiles %}

{% block title %} {{object.title}} {% endblock title %}

{% block content %}
<div class="container">
  <h1>{{object.title}}</h1>
  <p>
    {{object.content|safe}}
  </p>
</div>
{% endblock content %}

templates/home/filtro.html
{% extends "home/base_home.html" %}

{% load staticfiles %}

{% block title %} Lista por {{categoria}} {% endblock title %}

{% block content %}
<div class="container">
<h1>Lista de Entradas para {{categoria}}</h1>
  <nav>
    <div class="nav-wrapper">
      <div class="col s12">
        <ul class="left hide-on-med-and-down">
          <li>
            <a href="{% url 'home_app:entrada-lista' %}" class="breadcrumb">Todos</a>
          </li>
          {% for c in categorys %}
          <li>
            <a href="{% url 'home_app:entrada-filtro' c.name %}" class="breadcrumb">{{c.name}}</a>
          </li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </nav>

{% for e in entradas  %}
  <div class="row">
    <div class="col s12 m7">
      <div class="card small">
        <div class="card-image">
          <img src="{{ e.image.url }}">
          <span class="card-title">{{e.title}}</span>
        </div>
        <div class="card-content">
          <p>{{e.content|safe|truncatechars_html:300}}</p>
        </div>
        <div class="card-action">
          <a href="{% url 'home_app:entrada-detalle' e.slug %}">Ver Mas</a>
        </div>
      </div>
    </div>
  </div>
{% endfor %}
</div>
{% endblock content %}

templates/home/index.html
{% extends "home/base_home.html" %}

{% load staticfiles %}

{% block title %} Mi Proyecto Django {% endblock title %}

{% block content %}

  <h1>Bienvenido a mi proyecto con django</h1>

  <h3> Ahora el proyecto esta en un repositorio github </h3>
  
  <a href="{% url 'home_app:entrada-lista' %}" class="waves-effect waves-light btn">blog</a>

{% endblock content %}

templates/home/list_entrada.html
{% extends "home/base_home.html" %}

{% load staticfiles %}

{% block title %} Lista de entradas {% endblock title %}

{% block content %}
<div class="container">
<h1>Lista de Entradas</h1>
  <nav>
    <div class="nav-wrapper">
      <div class="col s12">
        <ul class="left hide-on-med-and-down">
          <li>
            <a href="{% url 'home_app:entrada-lista' %}" class="breadcrumb">Todos</a>
          </li>
          <li>
            <a href="{% url 'home_app:sugerencia-add' %}" class="breadcrumb">sugerencias</a>
          </li>
          {% for c in categorys %}
          <li>
            <a href="{% url 'home_app:entrada-filtro' c.name %}" class="breadcrumb">{{c.name}}</a>
          </li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </nav>

{% for e in entradas  %}
  <div class="row">
    <div class="col s12 m7">
      <div class="card small">
        <div class="card-image">
          <img src="{{ e.image.url }}">
          <span class="card-title">{{e.title}}</span>
        </div>
        <div class="card-content">
          <p>{{e.content|safe|truncatechars_html:300}}</p>
        </div>
        <div class="card-action">
          <a href="{% url 'home_app:entrada-detalle' e.slug %}">Ver Mas</a>
        </div>
      </div>
    </div>
  </div>
{% endfor %}
</div>
{% endblock content %}

templates/home/lista.html
{% extends "home/base_home.html" %}

{% load staticfiles %}

{% block title %} Lista de entradas {% endblock title %}

{% block content %}
<div class="container">
<h1>Lista de Entradas</h1>
  <nav>
    <div class="nav-wrapper">
      <div class="col s12">
        <ul class="left hide-on-med-and-down">
          <li>
            <a href="{% url 'home_app:entrada-lista' %}" class="breadcrumb">Todos</a>
          </li>
          {% for c in categorys %}
          <li>
            <a href="{% url 'home_app:entrada-filtro' c.name %}" class="breadcrumb">{{c.name}}</a>
          </li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </nav>

  <form method="get">{% csrf_token %}
    
    {{form.buscar}}
    
    <button type="submit" class="small radius bg-blanco button left">Buscar</button>
  </form>

{% for e in entradas  %}
  <div class="row">
    <div class="col s12 m7">
      <div class="card small">
        <div class="card-image">
          <img src="{{ e.image.url }}">
          <span class="card-title">{{e.title}}</span>
        </div>
        <div class="card-content">
          <p>{{e.content|safe|truncatechars_html:300}}</p>
        </div>
        <div class="card-action">
          <a href="{% url 'home_app:entrada-detalle' e.slug %}">Ver Mas</a>
        </div>
      </div>
    </div>
  </div>
{% endfor %}
</div>
{% endblock content %}

templates/home/lista_form.html
{% extends "home/base_home.html" %}

{% load staticfiles %}

{% block title %} Mi Proyecto Django {% endblock title %}

{% block content %}

<!-- <div class="row">
	<ul class="cd-pagination"> -->
            <!-- {% if page_obj.has_previous %}
                <li class="button">
                    <a href="?page={{ page_obj.previous_page_number }}"><i>Anterior</i></a>
                </li>
            {% else %}
                <li class="button">
                    <a class="disabled" href="#"><i>Anterior</i></a>
                </li>
            {% endif %} -->
            <!-- {% for num_page in paginator.page_range %}

                {% if page_obj.number|add:'-5' <= num_page and page_obj.number|add:"5" >= num_page %}

                    {%if page_obj.number == num_page %}

                        <li><a class="current" href="#">{{ num_page }}</a></li>
                    {% else %}
                        <li><a href="?page={{ num_page }}">{{ num_page }}</a></li>
                    {% endif %}
                {% endif %}
                  
            {% endfor %} -->
            
<!--         </ul>
</div> -->

<div class="row">
	<h3>Lista de Entradas</h3>
{% for e in lista_entradas  %}
  <div class="row">
    <div class="col s12 m7">
      <div class="card small">
        <div class="card-image">
          <img src="{{ e.image.url }}">
          <span class="card-title">{{e.title}}</span>
        </div>
        <div class="card-content">
          <p>{{e.content|safe|truncatechars_html:300}}</p>
        </div>
        <div class="card-action">
          <a href="{% url 'home_app:entrada-detalle' e.slug %}">Ver Mas</a>
        </div>
      </div>
    </div>
  </div>
{% endfor %}
</div>
<div class="row">
	<h3>Suscribete</h3>
	<form role="form" method="POST" enctype="multipart/form-data">{% csrf_token %}
	{{form}}
	<button type="submit">Suscribir</button>
 </form>
</div>

{% endblock content %}

templates/home/lista_sugerencia.html
{% extends "home/base_home.html" %}

{% load staticfiles %}

{% block title %} Mi Proyecto Django {% endblock title %}

{% block content %}

  <h1>Lista de sugerencias</h1>

  {% for s in sugerencias %}
  	<p>{{s.title}}</p>
  {%endfor%}

{% endblock content %}